# Linear Algebra with numpy
The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.

In [20]:
import numpy as np

In [21]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))

# Trace of matrix A
print("\nTrace of A:", np.trace(A))

# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))

# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))

print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [22]:
from numpy import linalg 

# Creating an array using array 
# function
a = np.array([[1, -2j], [2j, 5]])

print("Array is :",a)

# calculating an eigen value using eigh() function
c, d = linalg.eigh(a)

print("Eigen value is :", c)
print("Eigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is : [0.17157288 5.82842712]
Eigen value is : [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


# Using Numpy Arrays

In [23]:
a = np.array([1,2,3,4])
b = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
c = np.array([[(1,2,3,4),(5,6,7,8)],[(1,2,3,4),(5,6,7,8)]], dtype = float)
print(" a :", a)
print("\n b : ", b)
print("\n c : ",c)

 a : [1 2 3 4]

 b :  [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]

 c :  [[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[1. 2. 3. 4.]
  [5. 6. 7. 8.]]]


In [25]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr  = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr = np.random.random(3)
arr

array([0.49276187, 0.7699103 , 0.07711574])

In [31]:
arr = np.full((3,3),5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Vectorized Operations

Vectorized operations on NumPy allows the use of more optimal and pre-compiled functions and mathematical operations on NumPy array objects and data sequences.

In [32]:
# calculate the exponential value of each entry in a particular object.


import numpy as np
import timeit
import math
  
# vectorized operation
print("Time taken by vectorized operation : ", end = "")
%timeit np.exp(np.arange(150))
  
# non-vectorized operation
print("Time taken by non-vectorized operation : ", end = "")
%timeit [math.exp(item) for item in range(150)]

Time taken by vectorized operation : 3.12 µs ± 84.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time taken by non-vectorized operation : 29 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Universal Functions 

Universal functions in Numpy are simple mathematical functions. In NumPy, universal functions are instances of the numpy.ufunc class.

numpy.frompyfunc(function-name, input, output)

In [34]:
def product(a, b):
  return a*b
 
product = np.frompyfunc(product, 2, 1)
 
res = product([1, 2, 3, 4], [1,1,1,1])
print(res)

[1 2 3 4]


In [35]:
data = np.array([0, 30, 45])
 
rad = np.deg2rad(data)
 
# hyperbolic sine value
print('Sine hyperbolic values:')
hy_sin = np.sinh(rad)
print(hy_sin)
 
# inverse sine hyperbolic
print('Inverse Sine hyperbolic values:')
print(np.sin(hy_sin))
 
# hypotenuse
b = 3
h = 6
print('hypotenuse value for the right angled triangle:')
print(np.hypot(b, h))

Sine hyperbolic values:
[0.         0.54785347 0.86867096]
Inverse Sine hyperbolic values:
[0.         0.52085606 0.76347126]
hypotenuse value for the right angled triangle:
6.708203932499369


# Broadcasting and shape manupulation

Each universal function takes array inputs and produces array outputs by performing the core function element-wise on the inputs

### Manupulation: 
Numpy provides flexible tools to change the dimension of an array.

In [38]:
from numpy import array
# 2-dimensional
b = np.zeros((3,4))
array([[0., 0., 0., 0.],        
       [0., 0., 0., 0.],        
       [0., 0., 0., 0.]])
b.ndim
2
# 3-dimensional
c = np.ones((2,2,2))
array([[[1., 1.],         
        [1., 1.]],
         
        [[1., 1.],         
         [1., 1.]]])
c.ndim
3

3

### Reshape
1️⃣ reshape(a, newshape[, order]) →Gives a new shape to an array without changing its data.

2️⃣ ravel(a[, order]) →Return a contiguous flattened array.

3️⃣ ndarray.flat →A 1-D iterator over the array.

4️⃣ ndarray.flatten([order]) →Return a copy of the array collapsed into one dimension.

In [40]:
np.arange(8).reshape(2,2,2)
array([[[0, 1],         
        [2, 3]],          
        [[4, 5],         
        [6, 7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Boolean Mask

In [41]:
a = np.random.randint(-10, 10, 12).reshape(3, 4)
a

array([[-8, -1, -9,  5],
       [-4,  6,  4,  6],
       [-7, -6,  4,  9]])

# Date and Time in numpy

In [42]:
np.datetime64('today') # today's date
np.datetime64('now') # timestamp right now 

numpy.datetime64('2021-06-17T04:32:47')