# Introduction to Numpy and What is Numpy?

NumPy is a python package, primarily used for scientific and numerical computing. NumPy is a Python fundamental package used for efficient manipulations and operations on High-level mathematical functions, Multi-dimensional arrays, Linear algebra, Fourier Transformations, Random Number Capabilities, etc. NumPy is a combination of two words, coined by the blending of “Numerical” and “Python”.

In [61]:
#Import the numpy package under the name np and Print the numpy version and the configuration.
import numpy as np
print(np.__version__)
print(np.show_config)

1.19.2
<function show at 0x059A6580>


# Why Numpy Arrays
NumPy Arrays are faster than Python Lists.

In [62]:
import time
import sys
size =1000000
l1 = range(size)
l2 = range(size)
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time( )
res = [(x+y) for x,y in zip(l1,l2)]
print("Time take by List : ", (time.time()-start)*1000)
start = time.time( )
res1 = n1+n2
print("Time taken by numpy array : ", (time.time()-start)*1000)

Time take by List :  159.99603271484375
Time taken by numpy array :  0.0


# Numpy ndarrays Objects

In [63]:
array = np.array([10,38,85,57,78,97,32,35,11,65])
print(array.dtype)

int32


In [64]:
print("No. of dimensions: ", array.ndim) #Number of array dimensions.

No. of dimensions:  1


In [65]:
print("Shape of array: ", array.shape) #Number of elements in the array.

Shape of array:  (10,)


In [66]:
print("ItemSize: ", array.itemsize) #Length of one array element in bytes.

ItemSize:  4


In [67]:
array.nbytes #Total bytes consumed by the elements of the array.

40

In [68]:
# How to Convert a 1D array to a 2D array with 2 rows
randomarr = np.random.random(10)
randomarr = randomarr.reshape(2,5)
randomarr

array([[0.94981865, 0.70954612, 0.02395477, 0.22511516, 0.56437769],
       [0.67162376, 0.57767352, 0.58404268, 0.03973803, 0.40845863]])

# Array Indexing and Slicing

In [69]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [70]:
vector = np.arange(10,50,5)
print(vector)

[10 15 20 25 30 35 40 45]


# Memory layout of ndarray
An instance of the ndarray class is given a continuous segment in the memory. The memory allocation along with the indexing scheme then maps N-integers to an element of the array block. The range of index variation is given by the shape of the array and vice-versa.

In [71]:
a = np.array([[1, 5],[3, 9]])
b = np.array([[4, 6],[8, 1]])
print ("Array sum:\n", a + b)
print ("Array Minus:\n", a - b)
print ("Array multiplication:\n", a*b)
print ("Array (a^b) :\n", a**b)
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[ 5 11]
 [11 10]]
Array Minus:
 [[-3 -1]
 [-5  8]]
Array multiplication:
 [[ 4 30]
 [24  9]]
Array (a^b) :
 [[    1 15625]
 [ 6561     9]]
Matrix multiplication:
 [[44 11]
 [84 27]]


# Views and copies

In [72]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]],order ='F')
print("x is: \n", x)
y = x.copy()
print("y is :\n", y)
print("\nx is copied to y")

x is: 
 [[0 1 2 3]
 [4 5 6 7]]
y is :
 [[0 1 2 3]
 [4 5 6 7]]

x is copied to y


# Creating arrays

In [73]:
# Create a 2d array with 1 on the border and 0 inside
array = np.ones((4,4))
array[1:3,1:3]=0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [74]:
#How to add a border (filled with 0's) around an existing array?
array = np.zeros((4,4))
array[1:3,1:3]=1
print(array)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


# Array datatype

In [75]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [76]:
arr = np.array(["one", "two", "ten"]) #unicode string
print(arr.dtype)

<U3


In [77]:
arr = np.array([1.2, 4.5, 2.3]) #float
print(arr.dtype)

float64
